spring.application.name=gestionEtudiant
############################         server
server.port= 8082

############################         DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/gestionEtudiant
spring.datasource.username=urbansidev
spring.datasource.password=3xDaVs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.driverClassName=org.postgresql.Driver

############################         LOGGING
#logging.level.root=
#logging.level.com.university.gestionEtudiant=INFO